dataset_str:
  "WHULuoJiaWHUOMVSWAI(
    split='${dataset.whu_luojia_whuomvs_wai.val.split}',
    resolution=${dataset.whu_luojia_whuomvs_wai.val.dataset_resolution},
    principal_point_centered=${dataset.whu_luojia_whuomvs_wai.val.principal_point_centered},
    seed=${dataset.whu_luojia_whuomvs_wai.val.seed},
    transform='${dataset.whu_luojia_whuomvs_wai.val.transform}',
    data_norm_type='${dataset.whu_luojia_whuomvs_wai.val.data_norm_type}',
    ROOT='${dataset.whu_luojia_whuomvs_wai.val.ROOT}',
    dataset_metadata_dir='${dataset.whu_luojia_whuomvs_wai.val.dataset_metadata_dir}',
    overfit_num_sets=${dataset.whu_luojia_whuomvs_wai.val.overfit_num_sets},
    variable_num_views=${dataset.whu_luojia_whuomvs_wai.val.variable_num_views},
    num_views=${dataset.whu_luojia_whuomvs_wai.val.num_views},
    covisibility_thres=${dataset.whu_luojia_whuomvs_wai.val.covisibility_thres},
    covisibility_thres_max=${dataset.whu_luojia_whuomvs_wai.val.covisibility_thres_max},
    sampling_mode='${dataset.whu_luojia_whuomvs_wai.val.sampling_mode}')"
split: 'val'
dataset_resolution: ${dataset.resolution_val_whuomvs}
principal_point_centered: ${dataset.principal_point_centered}
seed: 777
transform: 'imgnorm'
data_norm_type: ${model.data_norm_type}
ROOT: ${root_data_dir}/whu_luojia_whuomvs
dataset_metadata_dir: ${mapanything_dataset_metadata_dir}
overfit_num_sets: null
variable_num_views: ${dataset.val.variable_num_views}
num_views: ${dataset.num_views}
covisibility_thres: 0.1
covisibility_thres_max: 1.0
sampling_mode: "random_walk"
