defaults:
  - default
  - task: images_only

# String for model factory
model_str: "da3"
# Model config
model_config:
  name: "da3_nested"
  # HF model string
  hf_model_name: "depth-anything/DA3NESTED-GIANT-LARGE-1.1"
  # Geometric input config
  geometric_input_config: ${model.task}
# Image Normalization Type
data_norm_type: "dinov2"
# DA3 checkpoint is already loaded in the inference wrapper
pretrained: null
# Torch hub force reload
torch_hub_force_reload: False
