defaults:
  - default
  - task: images_only

# String for model factory
model_str: "hunyuan"
# Model config
model_config:
  name: "hunyuan"
  # HF model string
  hf_model_name: "checkpoints/HunyuanWorld-Mirror"
  # Geometric input config
  geometric_input_config: ${model.task}
# Image Normalization Type
data_norm_type: "identity"
# Hunyuan checkpoint is already loaded in the inference wrapper
pretrained: null
# Torch hub force reload
torch_hub_force_reload: False
