defaults:
  - default
  - task: images_only

# String for model factory
model_str: "pi3x"
# Model config
model_config:
  name: "pi3x"
  # Geometric input config
  geometric_input_config: ${model.task}
  # PI3 model name or path
  pretrained_model_name_or_path: "checkpoints/pi3x"
# Image Normalization Type
data_norm_type: "identity"
# Pi3 checkpoint is already loaded in the inference wrapper
pretrained: null
# Torch hub force reload
torch_hub_force_reload: False


# /root/.cache/torch/hub/checkpoints/dinov2_vitg14_pretrain.pth