defaults:
  - default

# Number of views parameter for the multi-view datasets
num_views: 1

# Covisibility threshold for the multi-view datasets
covisibility_thres_min: 0.1
covisibility_thres_max: 1.0

# Sampling mode for the multi-view datasets (random_walk or greddy_chain)
sampling_mode: "random_walk" 

# Test Resolution
resolution_test_a3dscenes: ${dataset.resolution_options.518_many_ar}

# Test Set
test_dataset:
  "+ 1000 @ ${dataset.a3dscenes_wai.test.dataset_str}"
  