dataset_str:
  "UAVScenesWAI(
    split='${dataset.uavscenes_wai.train.split}',
    resolution=${dataset.uavscenes_wai.train.dataset_resolution},
    principal_point_centered=${dataset.uavscenes_wai.train.principal_point_centered},
    aug_crop=${dataset.uavscenes_wai.train.aug_crop},
    transform='${dataset.uavscenes_wai.train.transform}',
    data_norm_type='${dataset.uavscenes_wai.train.data_norm_type}',
    ROOT='${dataset.uavscenes_wai.train.ROOT}',
    dataset_metadata_dir='${dataset.uavscenes_wai.train.dataset_metadata_dir}',
    overfit_num_sets=${dataset.uavscenes_wai.train.overfit_num_sets},
    variable_num_views=${dataset.uavscenes_wai.train.variable_num_views},
    num_views=${dataset.uavscenes_wai.train.num_views},
    interval=${dataset.uavscenes_wai.train.interval})"
split: 'train'
dataset_resolution: ${dataset.resolution_train}
principal_point_centered: ${dataset.principal_point_centered}
aug_crop: 16
transform: 'colorjitter+grayscale+gaublur'
data_norm_type: ${model.data_norm_type}
ROOT: ${root_data_dir}/uavscenes
dataset_metadata_dir: ${mapanything_dataset_metadata_dir}
overfit_num_sets: null
variable_num_views: ${dataset.train.variable_num_views}
num_views: ${dataset.num_views}
interval: '[2,5,7,8,9,10,11,12,13,14,15]'
